[env:esp32doit-devkit-v1]
platform = espressif32
board = esp32doit-devkit-v1
framework = arduino
monitor_speed = 115200
upload_speed = 921600
lib_deps =
    mikalhart/TinyGPSPlus @ ^1.1.0
    bblanchon/ArduinoJson @ ^7.0.4
